image:
  file: .gitpod.dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
  - name: Prepare deps
    init: clojure -P -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.9.0"},cider/cider-nrepl {:mvn/version,"0.27.4"}}}'
  - name: Open README
    command: sleep 5 && code GITPOD_README.md && code src/a_quil_workflow/core.clj src/a_quil_workflow/drawing.clj GITPOD_README.md
